### PR TITLE
Adding in ability to dynamically reload a new config on a signal

### PR DESCRIPTION
**Pull request by jbendes**

### CODE REVIEW

**Comment by jbendes** [comment]
Addressing issue mentioned here: https://github.com/snsinfu/reverse-tunnel/issues/20
Okay so I've done what you mentioned in the issue above. Bear with me because this is my first time ever looking at golang haha. The issue is that the "old" servers (the ones binded to the old config ports) aren't getting destroyed on a new config reload. Any idea how to force that?

**Comment by snsinfu** [comment]
Thanks, that was fast!

Yeah, reconfiguration of the listening port is tricky. You can stop the server by calling `e.Close()`, but I don't think destroying an old server is the right thing to do.

The problem is that the old server may be tunneling active connections which some users prefer to keep alive and others do not. I think we should just reject a config update that requires the server to bind to another port. If a user want to change port, they can simply launch a new rtun-server along an old one and stop the old one later.

**Comment by jbendes** [comment]
Ahh I didn't mean the server bind port, I meant the udp/tcp source/dest port. It looks like the tunnels are being left alive. I think if a user deletes a tunnel from the yaml file, that tunnel should be closed. That seems like the only intent that the user could have, yeah?

**Comment by snsinfu** [comment]
Agreed. To stop a tunneling session, call `Close()` on the session object. Session objects are stored in `Action.store` ([here](https://github.com/snsinfu/reverse-tunnel/blob/286fb18f077182e01665cc118d4785c07b042975/server/action.go#L34)) but unfortunately you cannot examine existing sessions for validity in the current implementation.

**Comment by jbendes** [comment]
Do you have a recommendation on how to handle the race condition? Is there a concept of a mutex in golang?

**Comment by jbendes** [comment]
Scratch that, I see your mutex haha

**Comment by jbendes** [comment]
It looks like the UDP session object doesn't do anything for a close event. Is there something else we need to do to "close" the udp session?

**Comment by jbendes** [comment]
Okay pushed up a version that is closing sessions but I it's not actually what we want. It looks like even though it correctly closes the sessions, the ability to connect to the old ports is still there. My read of the code is suggesting we need to shut down the binder forever loop somehow?

**Comment by jbendes** [comment]
@snsinfu any thoughts on the above? I don't wanna run out of steam and then have this go inactive for a year haha. If you don't have time, that's totally fine but just wanted to ping you again about in case it fell off your radar

**Comment by snsinfu** [comment]
Oh, sorry I missed notification. I'll review and merge this PR soon!

**Comment by jbendes** [comment]
Okay but to be clear, the comments above are indicating that this PR isn't quite ready. This comment here: https://github.com/snsinfu/reverse-tunnel/pull/21#issuecomment-989563385

**Comment by snsinfu** [comment]
Ah, okay. Indeed some binders need to be stopped.

We should first add `Binder.Close()` function that stops the binder loop. [ln.AcceptTCP() here](https://github.com/snsinfu/reverse-tunnel/blob/286fb18f077182e01665cc118d4785c07b042975/server/tcp/binder.go#L49) blocks the loop, so we need to close the listener `ln` from `Binder.Close()` to stop the loop. Similarly for UDP.

Then, upon config update, we need to find out and close obsolete binders. A binder must correspond to a single (port, key) pair, so it can be done like closing old sessions.

It would be much cleaner to let binders (not Action) manage sessions, so that old sessions are automatically closed by closing an obsolete binder. But the code can be refactored later.

**Comment by snsinfu** [comment]
I will merge this PR and continue development in [dev-config-reload](https://github.com/snsinfu/reverse-tunnel/tree/dev-config-reload) branch. Thanks!

**Pull request merged**
